### PR TITLE
add safeCreate TextMeshBuilder method

### PR DESCRIPTION
**Pull request by meshantz**
addresses #22

### CODE REVIEW

**Comment by meshantz** [comment]
My apologies for the lacking description. Wanted to get the code in front of you, but had to run.

## Why

It seems important to be able to head off the memory error mentioned in #22, but it may be that not every use case wants to accept the overhead of doing so, particularly in the case of static text meshes where you know that your mesh will fit into memory.

## What

As such, I've left the interface for `TextMeshBuilder.create` alone to preserve backwards compatibility, and added a new wrapper function that is recommended for dynamic text payloads, at the expense of a pre-rendering check.

I used your code from the workaround (which you mentioned was thought up quickly) so I have no idea of how correct that is. I factored it to reside with what seemed like portions of your codebase it belongs with:
* the bytes calculation went into the `Compiler`
* the calculation of the command memory requirement went into the `Font`

## Room for improvement?

One thing I was unsure about was that the `MEMORY_BASE` constant duplicates the setting in `asconfig.json`. I'm not familiar with AssemblyScript, so I wasn't sure if there was a way to directly compile this in or not.

I also have not modified the `build/*` files. Wasn't sure how you handled this - on every push? merge? release?

**Comment by ycw** [comment]
> seems important to be able to head off the memory error mentioned 

agree, v4 will handle this *unrecoverable* err gracefully

> backward compatible

*breaking changes, `builder.create()`
- in v3, returns `Mesh | null`  (null if no mesh created, e.g. text are white spaces) 
- in v4, returns `Mesh | null | undefined` (undefined if wasm fails to process)

> MEMORY_BASE constant duplicates the setting in asconfig.json. I'm not familiar with AssemblyScript, so I wasn't sure if there was a way to directly compile this in or not

`ASC_MEMORY_BASE`, an AssemblyScript compile time constant 👍🏻

---
Take a look at https://ycw.github.io/Babylon.Font/examples/bare/, it's temporarily serving [v4](https://github.com/ycw/Babylon.Font/tree/next)

**Comment by meshantz** [comment]
> ASC_MEMORY_BASE, an AssemblyScript compile time constant 👍🏻

I saw that, but couldn't understand how to make it available to the typescript part of the codebase. I see now that you've got to [export it from the AssemblyScript](https://github.com/ycw/Babylon.Font/commit/228159e27155887fe72a77da6ba4592e4cfb7b0e#diff-682acd9c5a77f612609c859ab1a0f7819d13e142ed6cae9597e937295691ccf5R619).

> Take a look at https://ycw.github.io/Babylon.Font/examples/bare/, it's temporarily serving [v4](https://github.com/ycw/Babylon.Font/tree/next)

Looks good! Happily recovers after:  

image

Reading through your code to get a better feel for this project...

Is there anything from this PR you want to keep, or did you just want to close it?

**Comment by ycw** [comment]
https://github.com/ycw/Babylon.Font/releases/tag/v4.0.0

thanks.

**Comment by meshantz** [comment]
Out of curiosity, are you open to more PR's along the lines of making things clearer for an outsider to read? Since I'm poking around the code, there are a few things running through my mind as I go.

**Pull request closed without merging**
